spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: admin
    password: 2626
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/activity_logs

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: log-group
    auto-offset-reset: earliest
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
